- name: restart mysql, just in case
  action: service name=mysql state=restarted
  sudo: true

- name: restart apache, just in case
  action: service name=apache2 state=restarted
  sudo: true

- file: path={{ item }} mode=0777 owner={{ deploy_user }} group={{ deploy_user }} state=directory
  sudo: true
  with_items:
    - /var/cache/laravel
    - /var/cache/laravel/cache
    - /var/cache/laravel/clockwork
    - /var/cache/laravel/logs
    - /var/cache/laravel/meta
    - /var/cache/laravel/sessions
    - /var/cache/laravel/views

- file: path={{ item }} mode=0755 owner={{ deploy_user }} group={{ deploy_user }} state=directory
  sudo: true
  with_items:
    - /var/www/laravel

- synchronize: src=../src/ dest=/var/www/laravel/
  sudo: false

- name: artisan optimize
  command: chdir=/var/www/laravel php artisan optimize
  sudo: false

- name: run migrations
  command: chdir=/var/www/laravel php artisan migrate
  sudo: false

- name: run benchmarks
  command: chdir=/var/www/laravel bash benchmark.sh
  sudo: false

- name: run benchmarks again
  command: chdir=/var/www/laravel bash benchmark.sh
  sudo: false
