- file: path={{ item }} mode=0777 owner={{ deploy_user }} group={{ deploy_user }} state=directory
  sudo: true
  with_items:
    - /var/cache/laravel
    - /var/cache/laravel/cache
    - /var/cache/laravel/clockwork
    - /var/cache/laravel/logs
    - /var/cache/laravel/meta
    - /var/cache/laravel/sessions
    - /var/cache/laravel/views

- file: path={{ item }} mode=0755 owner={{ deploy_user }} group={{ deploy_user }} state=directory
  sudo: true
  with_items:
    - /var/www/laravel

- synchronize: src=../src/ dest=/var/www/laravel/
  sudo: false
